# -*- coding: utf-8 -*-
"""analisis_secop_completo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-s1LCCHQKdb5cI6OicRgsxYalWGZzEgN

# **Análisis de Datos SECOP - Colombia**


## Análisis de Contratación Pública

**¿Qué vamos a hacer?**
-  Descargar datos reales de contratación pública
-  Limpiar y procesar la información
-  Crear visualizaciones interactivas
-  Analizar redes de colaboración
-  Detectar patrones interesantes

**Solo ejecuta las celdas una por una y disfruta del análisis**

## Instalación de librerias
"""

#  INSTALACIÓN Y CONFIGURACIÓN INICIAL
print(" Configurando entorno de análisis...")

# Instalar librerías necesarias
!pip install fuzzywuzzy python-Levenshtein networkx plotly kaleido -q

# ====================================================================
# LIBRERÍAS PARA ANÁLISIS DE DATOS, SOLICITUDES Y VISUALIZACIÓN
# ====================================================================

import pandas as pd        # Manipulación y análisis de datos (tablas tipo Excel o CSV)
import numpy as np          # Cálculos numéricos y manejo de arreglos (vectores, matrices)
import requests             # Envío de solicitudes HTTP (consultar APIs o páginas web)
import time                 # Control de tiempos y pausas en la ejecución del programa
import warnings             # Ocultar o controlar advertencias del sistema

# ====================================================================
# LIBRERÍAS PARA VISUALIZACIÓN INTERACTIVA CON PLOTLY
# ====================================================================

import plotly.express as px # Gráficos interactivos sencillos (barras, dispersión, mapas, etc.)
import plotly.graph_objects as go   # Gráficos avanzados y personalizados (más control)
from plotly.subplots import make_subplots  # Permite combinar varios gráficos en una misma figura
import plotly.io as pio     # Configuración de visualización y exportación (HTML, PNG, etc.)
#import matplotlib.pyplot as plt

# ====================================================================
# LIBRERÍAS PARA ANÁLISIS DE REDES, COMBINACIONES Y COINCIDENCIAS DE TEXTO
# ====================================================================

import networkx as nx       # Creación y análisis de grafos/redes (nodos y relaciones)
import itertools            # Combinaciones, permutaciones y operaciones sobre iteradores
from fuzzywuzzy import fuzz, process  # Comparación de texto difusa (emparejamiento aproximado)

# ====================================================================
# LIBRERÍA PARA MOSTRAR BARRAS DE PROGRESO
# ====================================================================

from tqdm import tqdm        # Barra de progreso en loops largos para seguimiento visual

# Configuraciones
pio.renderers.default = "colab"
warnings.filterwarnings('ignore')

print("✅ Herramientas listas!")

"""## Descarga de datos"""

def descargar_datos(cuantos_registros=100000):
    """
    Descarga una muestra pequeña de datos de SECOP
    Perfecto para empezar a aprender
    """
    print(f"Descargando {cuantos_registros:,} contratos de ejemplo...")

    # URL oficial de datos del gobierno
    url = "https://www.datos.gov.co/resource/jbjy-vk9h.json"

    # Configuración simple
    params = {
        "$limit": cuantos_registros,
        "$where": "departamento = 'Distrito Capital de Bogotá'"
    }

    try:
        # Descargar datos
        response = requests.get(url, params=params, timeout=30)
        datos = response.json()

        # Convertir a tabla
        df = pd.DataFrame(datos)

        print(f"¡Descarga exitosa! {len(df):,} contratos obtenidos")
        return df

    except Exception as error:
        print(f"Error al descargar: {error}")
        return pd.DataFrame()

# Descargar datos
df_contratos = descargar_datos(100000)

"""## Exploración de datos"""

print("Primeros 3 contratos:")
print(df_contratos.head(3))

# Ver las primeras filas
pd.set_option('display.max_columns', None)

print("Primeros 3 contratos:")
print(df_contratos.head(3))

# Ver información básica
print("Información básica:")
print(f"   • Número de filas: {len(df_contratos):,}")
print(f"   • Número de columnas: {len(df_contratos.columns)}")

# Ver nombres de columnas
print("\nColumnas disponibles:")
for i, col in enumerate(df_contratos.columns, 1):
    print(f"   {i:2d}. {col}")

# Imprimir el tipo de variable

pd.set_option('display.max_columns', None)   # Mostrar todas las columnas
pd.set_option('display.width', None)         # Evita que se corten por ancho
pd.set_option('display.max_colwidth', None)  # Muestra todo el texto de cada columna

print("\nTipos de datos de todas las columnas:\n")
print(df_contratos.dtypes)

"""# Analisis de variables"""

# Número total de contratos
print("Número total de registros:", df_contratos["id_contrato"].count())

# Cuántos contratos están repetidos
duplicados = df_contratos["id_contrato"].duplicated().sum()
print("Contratos duplicados:", duplicados)

# Cuántos valores nulos tiene la columna
print("Valores nulos en id_contrato:", df_contratos["id_contrato"].isna().sum())

# Ver el rango de años que cubren los contratos
print(df_contratos['fecha_firma'].dt.year.min(), df_contratos['fecha_firma'].dt.year.max())

"""☝
*   **Problema:** El código intenta acceder a la columna 'fecha_firma' en el DataFrame df_contratos, pero esta columna no existe en los datos cargados
*   **Causa:** Hay un error de tipeo en el nombre de la columna o los datos no contienen esa columna específica - necesitas verificar el nombre exacto usando df_contratos.columns para ver las columnas disponibles

**Paso 1: Primero ejecuten este código para ver qué columnas tienen disponibles:**
"""

print("Columnas disponibles:")
print(df_contratos.columns.tolist())

"""**Paso 2: Una vez identifiquen el nombre correcto de la columna de fecha, reemplacen 'fecha_firma' en el código original por el nombre exacto que aparezca en la lista (por ejemplo, podría ser 'fecha_de_firma', 'fecha_contrato', etc.)**

"""

try:
    # Intentar ejecutar el código original
    print(df_contratos['fecha_firma'].dt.year.min(), df_contratos['fecha_firma'].dt.year.max())
except KeyError:
    # Si la columna no existe, mostrar las disponibles y solicitar el nombre correcto
    print("Error: La columna 'fecha_firma' no existe.")
    print("\nColumnas disponibles en el DataFrame:")
    print(df_contratos.columns.tolist())

    # Solicitar el nombre correcto
    nombre_columna = input("\nIngrese el nombre exacto de la columna de fecha que desea usar: ")

    try:
        # Convertir a datetime si no lo es ya
        df_contratos[nombre_columna] = pd.to_datetime(df_contratos[nombre_columna], errors='coerce')

        # Ejecutar con la columna correcta
        print(f"\nRango de años en la columna '{nombre_columna}':")
        print(df_contratos[nombre_columna].dt.year.min(), df_contratos[nombre_columna].dt.year.max())

    except AttributeError:
        print(f"Error: La columna '{nombre_columna}' no contiene datos de fecha válidos.")
    except Exception as e:
        print(f"Error procesando la columna '{nombre_columna}': {e}")

"""**Nota:** Vamos a filtrar los datos desde **2021** en adelante, ya que los datos anteriores contienen demasiados errores y valores inconsistentes que afectan la calidad del análisis

"""

# Filtrar datos desde 2021 en adelante para trabajar con información más confiable
# Los datos anteriores contienen demasiados errores

# Convertir la columna a formato de fecha
df_contratos['fecha_de_firma'] = pd.to_datetime(df_contratos['fecha_de_firma'])

# Filtrar desde 2021
df_contratos = df_contratos[df_contratos['fecha_de_firma'].dt.year >= 2021]

# Ver el rango de años filtrados
print("Rango de años después del filtro:")
print(df_contratos['fecha_de_firma'].dt.year.min(), df_contratos['fecha_de_firma'].dt.year.max())

"""Antes de continuar con el análisis, es importante conocer los **diferentes estados** que pueden tener los contratos en el dataset. Esto nos ayudará a entender el ciclo de vida de los contratos y filtrar la información según el estado que nos interese analizar."""

# Ver valores únicos de estado_contrato
print("=== VALORES ÚNICOS EN ESTADO_CONTRATO ===")
estados_unicos = df_contratos['estado_contrato'].value_counts()
print(estados_unicos)

print(f"\nTotal de estados diferentes: {df_contratos['estado_contrato'].nunique()}")
print(f"Valores únicos: {df_contratos['estado_contrato'].unique()}")

# Visualización
plt.figure(figsize=(10, 6))
plt.bar(estados_unicos.index, estados_unicos.values, color='lightblue')
plt.title('Distribución de Estados de Contrato')
plt.xlabel('Estado del Contrato')
plt.ylabel('Número de Contratos')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""⏩ Ahora crearemos una gráfica que muestre la relación entre las fechas de firma y los contratos (usando el id_contrato como identificador único) para analizar la distribución temporal de la contratación pública.

"""

# Eliminar contratos duplicados basados en id_contrato para asegurar que cada contrato sea único
df_contratos_unicos = df_contratos.drop_duplicates(subset=['id_contrato'])

# Contar cuántos contratos únicos se firmaron por fecha
contratos_por_fecha = df_contratos_unicos['fecha_de_firma'].value_counts().sort_index()

# Crear la gráfica
plt.figure(figsize=(12, 6))
plt.plot(contratos_por_fecha.index, contratos_por_fecha.values)
plt.title('Número de Contratos Únicos Firmados por Fecha')
plt.xlabel('Fecha de Firma')
plt.ylabel('Cantidad de Contratos')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""Necesitas importar las librerías para hacer gráficas. Agrega esto al inicio en IMPORTACIÓN DE LIBRERIAS

**import matplotlib.pyplot as plt**
"""

# Eliminar contratos duplicados basados en id_contrato para asegurar que cada contrato sea único
df_contratos_unicos = df_contratos.drop_duplicates(subset=['id_contrato'])

# Contar cuántos contratos únicos se firmaron por fecha
contratos_por_fecha = df_contratos_unicos['fecha_de_firma'].value_counts().sort_index()

# Crear la gráfica
plt.figure(figsize=(12, 6))
plt.plot(contratos_por_fecha.index, contratos_por_fecha.values)
plt.title('Número de contratos únicos firmados por fecha')
plt.xlabel('Fecha de Firma')
plt.ylabel('Cantidad de Contratos')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""Ahora crearemos una gráfica de barras que nos muestre cuántos **contratos únicos se firmaron cada año**. Esto nos permitirá identificar fácilmente en qué años hubo mayor o menor actividad de contratación pública."""

# Agrupar contratos únicos por año
contratos_por_año = df_contratos_unicos['fecha_de_firma'].dt.year.value_counts().sort_index()

# Crear la gráfica de barras
plt.figure(figsize=(10, 6))
plt.bar(contratos_por_año.index, contratos_por_año.values, color='skyblue')
plt.title('Número de Contratos Únicos por Año')
plt.xlabel('Año')
plt.ylabel('Cantidad de Contratos')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Mostrar los números exactos
print("Contratos por año:")
for año, cantidad in contratos_por_año.items():
    print(f"{año}: {cantidad} contratos")

"""Ahora crearemos un gráfico de torta (pie chart) que nos muestre qué porcentaje de **contratos únicos corresponde a cada sector**. Esto nos ayudará a identificar cuáles son los sectores que más contratan."""

# Contar contratos únicos por sector
contratos_por_sector = df_contratos_unicos['sector'].value_counts()

# Crear el gráfico de torta
plt.figure(figsize=(8, 8))
plt.pie(contratos_por_sector.values, labels=contratos_por_sector.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribución de Contratos Únicos por Sector')
plt.axis('equal')  # Para que el círculo se vea perfecto
plt.tight_layout()
plt.show()

# Mostrar los números exactos
print("Contratos por sector:")
for sector, cantidad in contratos_por_sector.items():
    print(f"{sector}: {cantidad} contratos")

"""El gráfico anterior presenta **saturación visual con porcentajes superpuestos** y demasiadas categorías pequeñas, lo que dificulta su lectura e interpretación. Necesitamos crear una versión más limpia y clara."""

# Contar contratos únicos por sector
contratos_por_sector = df_contratos_unicos['sector'].value_counts()

# Crear gráfico de barras horizontales para mejor visualización
plt.figure(figsize=(12, 8))
contratos_por_sector.plot(kind='barh', color='skyblue')
plt.title('Número de Contratos Únicos por Sector')
plt.xlabel('Cantidad de Contratos')
plt.ylabel('Sector')
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

# Contar contratos únicos por sector
contratos_por_sector = df_contratos_unicos['sector'].value_counts()

# Tomar solo los 5 sectores principales para mejor visualización
top_sectores = contratos_por_sector.head(5)

# Crear el gráfico de torta mejorado
plt.figure(figsize=(12, 8))
colors = ['#1f77b4', '#aec7e8', '#2ca02c', '#98df8a', '#17becf', '#9edae5', '#2e8b57', '#66cdaa', '#4682b4', '#87ceeb']

plt.pie(top_sectores.values,
        labels=top_sectores.index,
        autopct='%1.1f%%',
        startangle=90,
        colors=colors,
        textprops={'fontsize': 10})
plt.title('Top 5 sectores con más contratos únicos', fontsize=14, pad=20)
plt.tight_layout()
plt.show()

# Mostrar los números exactos
print("Top 5 sectores con más contratos:")
for sector, cantidad in top_sectores.items():
    print(f"{sector}: {cantidad} contratos")

"""# Aplicación de Lenguaje natural como asistente de programación

**Prompts:** "Tengo un dataset de contratos públicos con las columnas valor_del_contrato, valor_pagado, valor_pendiente_de_pago. Ayúdame a analizar la distribución de estos valores y detectar posibles inconsistencias o valores atípicos."
"""

# Análisis de valores monetarios
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Estadísticas básicas de valores monetarios
columnas_monetarias = ['valor_del_contrato', 'valor_pagado', 'valor_pendiente_de_pago', 'valor_facturado']

print("=== ESTADÍSTICAS DE VALORES MONETARIOS ===")
for col in columnas_monetarias:
    if col in df_contratos.columns:
        print(f"\n{col.upper()}:")
        print(f"Promedio: ${df_contratos[col].mean():,.0f}")
        print(f"Mediana: ${df_contratos[col].median():,.0f}")
        print(f"Máximo: ${df_contratos[col].max():,.0f}")
        print(f"Mínimo: ${df_contratos[col].min():,.0f}")

# Visualización de distribución
fig, axes = plt.subplots(2, 2, figsize=(15, 10))
axes = axes.flatten()

for i, col in enumerate(columnas_monetarias[:4]):
    if col in df_contratos.columns:
        # Usar escala logarítmica para mejor visualización
        df_contratos[col].hist(bins=50, ax=axes[i], log=True)
        axes[i].set_title(f'Distribución de {col}')
        axes[i].set_xlabel('Valor (escala log)')
        axes[i].set_ylabel('Frecuencia')

plt.tight_layout()
plt.show()

# Detectar valores atípicos
print("\n=== DETECCIÓN DE VALORES ATÍPICOS ===")
for col in ['valor_del_contrato']:
    Q1 = df_contratos[col].quantile(0.25)
    Q3 = df_contratos[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df_contratos[(df_contratos[col] < Q1 - 1.5*IQR) | (df_contratos[col] > Q3 + 1.5*IQR)]
    print(f"{col}: {len(outliers)} valores atípicos detectados")

# Limpiar y convertir columnas monetarias
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Función para limpiar valores monetarios
def limpiar_valor_monetario(valor):
    if pd.isna(valor):
        return 0
    if isinstance(valor, str):
        # Remover caracteres no numéricos excepto puntos y comas
        valor_limpio = ''.join(c for c in valor if c.isdigit() or c in '.,')
        # Si está vacío después de limpiar, retornar 0
        if not valor_limpio:
            return 0
        try:
            # Convertir a float
            return float(valor_limpio.replace(',', ''))
        except:
            return 0
    return valor

# Limpiar columnas monetarias
columnas_monetarias = ['valor_del_contrato', 'valor_pagado', 'valor_pendiente_de_pago', 'valor_facturado']

print("Limpiando datos monetarios...")
for col in columnas_monetarias:
    if col in df_contratos.columns:
        df_contratos[col] = df_contratos[col].apply(limpiar_valor_monetario)

print("=== ESTADÍSTICAS DE VALORES MONETARIOS ===")
for col in columnas_monetarias:
    if col in df_contratos.columns:
        print(f"\n{col.upper()}:")
        print(f"Promedio: ${df_contratos[col].mean():,.0f}")
        print(f"Mediana: ${df_contratos[col].median():,.0f}")
        print(f"Máximo: ${df_contratos[col].max():,.0f}")
        print(f"Mínimo: ${df_contratos[col].min():,.0f}")

# Visualización de distribución
fig, axes = plt.subplots(2, 2, figsize=(15, 10))
axes = axes.flatten()

for i, col in enumerate(columnas_monetarias[:4]):
    if col in df_contratos.columns:
        # Filtrar valores > 0 para escala logarítmica
        valores_positivos = df_contratos[df_contratos[col] > 0][col]
        valores_positivos.hist(bins=50, ax=axes[i], log=True)
        axes[i].set_title(f'Distribución de {col}')
        axes[i].set_xlabel('Valor (escala log)')
        axes[i].set_ylabel('Frecuencia')

plt.tight_layout()
plt.show()

# Detectar valores atípicos
print("\n=== DETECCIÓN DE VALORES ATÍPICOS ===")
for col in ['valor_del_contrato']:
    Q1 = df_contratos[col].quantile(0.25)
    Q3 = df_contratos[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df_contratos[(df_contratos[col] < Q1 - 1.5*IQR) | (df_contratos[col] > Q3 + 1.5*IQR)]
    print(f"{col}: {len(outliers)} valores atípicos detectados")

"""**Prompts:** "Mi dataset tiene fechas de firma, inicio y fin de contratos. Quiero analizar patrones temporales: ¿En qué meses/años hay más contratación? ¿Cuál es la duración promedio de los contratos?"
"""

# Análisis temporal de contratación
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Convertir columnas de fechas a datetime
print("Convirtiendo fechas...")
df_contratos['fecha_de_firma'] = pd.to_datetime(df_contratos['fecha_de_firma'], errors='coerce')
df_contratos['fecha_de_inicio_del_contrato'] = pd.to_datetime(df_contratos['fecha_de_inicio_del_contrato'], errors='coerce')
df_contratos['fecha_de_fin_del_contrato'] = pd.to_datetime(df_contratos['fecha_de_fin_del_contrato'], errors='coerce')

# Filtrar datos desde 2021 (como establecimos antes)
df_temp = df_contratos[df_contratos['fecha_de_firma'].dt.year >= 2021].copy()

# Calcular duración de contratos
df_temp['duracion_dias'] = (df_temp['fecha_de_fin_del_contrato'] - df_temp['fecha_de_inicio_del_contrato']).dt.days

print("=== ANÁLISIS TEMPORAL DE CONTRATOS ===")

# Crear visualizaciones
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1. Contratos por año
contratos_año = df_temp['fecha_de_firma'].dt.year.value_counts().sort_index()
axes[0,0].bar(contratos_año.index, contratos_año.values, color='skyblue')
axes[0,0].set_title('Contratos por Año')
axes[0,0].set_xlabel('Año')
axes[0,0].set_ylabel('Número de Contratos')
axes[0,0].grid(True, alpha=0.3)

# 2. Contratos por mes
contratos_mes = df_temp['fecha_de_firma'].dt.month.value_counts().sort_index()
meses = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
axes[0,1].bar(contratos_mes.index, contratos_mes.values, color='lightgreen')
axes[0,1].set_title('Contratos por Mes (Todos los Años)')
axes[0,1].set_xlabel('Mes')
axes[0,1].set_ylabel('Número de Contratos')
axes[0,1].set_xticks(range(1, 13))
axes[0,1].set_xticklabels(meses, rotation=45)
axes[0,1].grid(True, alpha=0.3)

# 3. Valor total por año
valor_año = df_temp.groupby(df_temp['fecha_de_firma'].dt.year)['valor_del_contrato'].sum()
axes[1,0].bar(valor_año.index, valor_año.values/1e9, color='orange')
axes[1,0].set_title('Valor Total Contratado por Año')
axes[1,0].set_xlabel('Año')
axes[1,0].set_ylabel('Valor (Miles de Millones COP)')
axes[1,0].grid(True, alpha=0.3)

# 4. Duración promedio de contratos
# Filtrar duraciones válidas (mayores a 0 y menores a 3650 días = 10 años)
df_duracion = df_temp[(df_temp['duracion_dias'] > 0) & (df_temp['duracion_dias'] < 3650)]
duracion_año = df_duracion.groupby(df_duracion['fecha_de_firma'].dt.year)['duracion_dias'].mean()
axes[1,1].plot(duracion_año.index, duracion_año.values, marker='o', color='red', linewidth=2)
axes[1,1].set_title('Duración Promedio de Contratos por Año')
axes[1,1].set_xlabel('Año')
axes[1,1].set_ylabel('Días')
axes[1,1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Estadísticas detalladas
print("=== ESTADÍSTICAS TEMPORALES DETALLADAS ===")

print(f"\n📅 CONTRATOS POR AÑO:")
for año, cantidad in contratos_año.items():
    valor_total = valor_año.get(año, 0)
    print(f"  {año}: {cantidad:,} contratos - ${valor_total:,.0f} COP")

print(f"\n📅 CONTRATOS POR MES (promedio todos los años):")
for i, mes in enumerate(meses, 1):
    cantidad = contratos_mes.get(i, 0)
    print(f"  {mes}: {cantidad:,} contratos")

print(f"\n⏱️ DURACIÓN DE CONTRATOS:")
duraciones_validas = df_temp['duracion_dias'][(df_temp['duracion_dias'] > 0) & (df_temp['duracion_dias'] < 3650)]
print(f"  Duración promedio: {duraciones_validas.mean():.0f} días ({duraciones_validas.mean()/30:.1f} meses)")
print(f"  Duración mediana: {duraciones_validas.median():.0f} días ({duraciones_validas.median()/30:.1f} meses)")
print(f"  Duración mínima: {duraciones_validas.min():.0f} días")
print(f"  Duración máxima: {duraciones_validas.max():.0f} días ({duraciones_validas.max()/365:.1f} años)")

# Análisis adicional: días de la semana
print(f"\n📅 CONTRATOS POR DÍA DE LA SEMANA:")
dias_semana = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
contratos_dia_semana = df_temp['fecha_de_firma'].dt.day_of_week.value_counts().sort_index()
for i, dia in enumerate(dias_semana):
    cantidad = contratos_dia_semana.get(i, 0)
    print(f"  {dia}: {cantidad:,} contratos")

# Picos y valles de contratación
mes_mayor = contratos_mes.idxmax()
mes_menor = contratos_mes.idxmin()
año_mayor = contratos_año.idxmax()
año_menor = contratos_año.idxmin()

print(f"\n🔍 PATRONES IDENTIFICADOS:")
print(f"  Mes con más contratación: {meses[mes_mayor-1]} ({contratos_mes[mes_mayor]:,} contratos)")
print(f"  Mes con menos contratación: {meses[mes_menor-1]} ({contratos_mes[mes_menor]:,} contratos)")
print(f"  Año con más contratación: {año_mayor} ({contratos_año[año_mayor]:,} contratos)")
print(f"  Año con menos contratación: {año_menor} ({contratos_año[año_menor]:,} contratos)")

"""**Prompts:** "Tengo datos de entidades contratantes y sectores. Ayúdame a identificar qué entidades contratan más, en qué sectores se concentra el gasto público y crear visualizaciones claras."

**Prompts:** "Mi dataset incluye modalidades de contratación (mínima cuantía, licitación, etc.). ¿Puedes ayudarme a analizar qué modalidades se usan más y si hay relación con los montos?"

**Prompts:** "Tengo un dataset de contratos con muchas columnas. Ayúdame a identificar datos faltantes, inconsistencias entre fechas, y problemas de calidad que deba limpiar antes del análisis."

**Prompts:** "Quiero analizar los proveedores: ¿Hay concentración en pocos proveedores? ¿Qué tipos de empresas (pymes vs grandes) obtienen más contratos?"

# ¡Análisis Completado!

## Lo que has logrado:
- **Trabajaste con datos reales** de contratación pública colombiana (SECOP)
- **Limpiaste y transformaste** datos complejos con valores mixtos
- **Filtraste información** desde 2021 para mayor calidad de datos
- **Creaste múltiples visualizaciones** (gráficos de barras, tortas, líneas temporales)
- **Analizaste patrones temporales** de contratación por años, meses y sectores
- **Exploraste distribuciones monetarias** y detectaste valores atípicos
- **Investigaste proveedores** y su participación en el mercado público

## Lo que descubriste:
- **Patrones estacionales** en la contratación pública
- **Sectores dominantes** en la contratación (Transporte, TIC, etc.)
- **Distribución de contratos** entre PYMES y grandes empresas
- **Valores típicos y atípicos** en los montos contratados
- **Estados de contratos** y su distribución

## Próximos pasos sugeridos:
1. **Experimenta** con diferentes filtros (sectores específicos, rangos de valores)
2. **Personaliza** las visualizaciones con paletas de colores profesionales
3. **Profundiza** en análisis por departamentos o ciudades específicas
4. **Analiza correlaciones** entre variables (modalidad vs valor, sector vs duración)
5. **Exporta** tus gráficos y datos limpios para presentaciones

## Ideas para expandir:
- Analizar eficiencia de diferentes modalidades de contratación
- Detectar patrones sospechosos o anomalías en la contratación
- Comparar rendimiento de PYMES vs grandes empresas
- Crear análisis predictivos de tendencias futuras
- Desarrollar indicadores de transparencia y competencia

## Habilidades desarrolladas:
- **Limpieza de datos** con pandas
- **Visualización** con matplotlib
- **Análisis exploratorio** de datasets complejos
- **Interpretación** de datos gubernamentales
- **Pensamiento analítico** aplicado a políticas públicas

---

**¡Has completado un análisis profesional de datos públicos!**
*Estas habilidades son altamente valoradas en ciencia de datos, consultoría y análisis de políticas públicas.*
"""